const codices = [
    'CODEX A',
    'CODEX B',
    'CODEX C',
    'CODEX D',
    'CODEX E',
    'CODEX F',
    'CODEX G',
    'CODEX H',
    'CODEX I',
    'CODEX J',
    'CODEX K',
    'CODEX L',
    'CODEX M',
    'CODEX N',
    'CODEX O',
    'CODEX P',
    'CODEX Q',
    'CODEX R',
    'CODEX S',
    'CODEX T',
    'CODEX U',
    'CODEX V',
    'CODEX W',
    'CODEX X',
    'CODEX Y',
    'CODEX Z',
    'Appendix A: NPC Codex'
]
module.exports.codices = codices;